name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag academy:$(date +%s)
    - name: List Docker Images
      run: docker images
shell: bash
