apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: academy
  name: stand-reader
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps","secrets"]
    verbs: ["list","get","watch"]